import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "./provider/page";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// ${geistMono.variable} ${geistSans.variable}

export const metadata = {
  title: "Mahmudul-Keen-Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F8FAFC]">
        <Providers>
          <Navbar></Navbar>
        <main className="container mx-auto ">

        {children}
        </main>
        <Footer></Footer>
        </Providers>
        <Toaster />
        </body>
    </html>
  );
}
